Repository codeready-toolchain/host-operator, pull requests merged in 2019-09, with the labels that each got.

#60 fix JSONPath syntax for additionalPrinterColumns
  deploy/crds/toolchain_v1alpha1_usersignup.yaml
Labels: approved, size/XS

#59 chore: move custom assertions and doubles to toolchain-common repo
  go.mod
  go.sum
  pkg/controller/masteruserrecord/masteruserrecord_controller_test.go
  pkg/controller/masteruserrecord/sync_test.go
  test/doubles.go
  test/e2e/masteruserrecord_test.go
  test/masteruserrecord/assertion.go
  test/masteruserrecord/doubles.go
  test/useraccount/assertion.go
  test/useraccount/doubles.go
Labels: approved, size/L

#62 chore: replace git.apache.org/thrift.git by github.com/apache/thrift
  go.mod
Labels: approved, size/XS

#61 Add yaml for UserSignup CRD and example
  deploy/crds/toolchain_v1alpha1_usersignup.yaml
  examples/toolchain_v1alpha1_usersignup_cr.yaml
  go.mod
  go.sum
  test/e2e/usersignup_test.go
Labels: approved, size/M

#58 chore(CRT-222): move e2e tests to toolchain-e2e
  README.adoc
  make/test.mk
  test/e2e/doc.go
  test/e2e/kubefedcluster_test.go
  test/e2e/main_test.go
  test/e2e/masteruserrecord_test.go
  test/e2e/usersignup_test.go
  test/e2e/wait_util.go
Labels: approved, size/XXL

#63 configure 'unparam' linter and clean code accordingly
  .golangci.yml
  pkg/controller/masteruserrecord/masteruserrecord_controller.go
  pkg/controller/masteruserrecord/masteruserrecord_controller_test.go
  pkg/controller/masteruserrecord/sync_test.go
  pkg/controller/usersignup/usersignup_controller.go
Labels: approved, size/M

#64 add sample templates to be created at operator startup
  .gitignore
  go.mod
  go.sum
  make/go.mk
  make/test.mk
  openshift-ci/Dockerfile.tools
  templates/advanced-code.yml
  templates/advanced-dev.yml
  templates/advanced-stage.yml
  templates/basic-code.yml
  templates/basic-dev.yml
  templates/basic-stage.yml
  templates/templates_bindata_test.go
  tools.go
Labels: approved, size/L

#65 reorg NSTemplateTier files
  .gitignore
  deploy/nstemplatetiers/advanced-code.yaml
  deploy/nstemplatetiers/advanced-dev.yaml
  deploy/nstemplatetiers/advanced-stage.yaml
  deploy/nstemplatetiers/basic-code.yaml
  deploy/nstemplatetiers/basic-dev.yaml
  deploy/nstemplatetiers/basic-stage.yaml
  go.mod
  go.sum
  make/clean.mk
  make/go.mk
  make/lint.mk
  pkg/templates/template_contents_test.go
Labels: approved, size/L

#66 chore: when running in CI use built image in e2e tests
  make/test.mk
Labels: approved, size/XS

#67 generate metadata with git short commits
  .gitignore
  go.mod
  go.sum
  make/clean.mk
  make/go.mk
  pkg/templates/template_contents_test.go
  pkg/templates/templates_test.go
Labels: approved, size/L

#70 update CRD after NSTemplateSet/NSTemplateTier Namespace type refactoring
  deploy/crds/toolchain_v1alpha1_nstemplatetier.yaml
  go.mod
  go.sum
  pkg/controller/usersignup/usersignup_controller.go
Labels: approved, size/L

#71 chore: add crd suffix to CRD file names-it's expected by operator-sdk csv generator
  deploy/crds/core_v1beta1_kubefedcluster_crd.yaml
  deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
  deploy/crds/toolchain_v1alpha1_nstemplatetier_crd.yaml
  deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
Labels: approved, size/XS
