Repository codeready-toolchain/host-operator, pull requests merged in 2019-07, with the labels that each got.

#24 Add conditions to MUR status
  deploy/crds/toolchain_v1alpha1_masteruserrecord.yaml
  examples/toolchain_v1alpha1_masteruserrecord_cr.yaml
  go.mod
  go.sum
  make/clean.mk
Labels: approved, lgtm, size/M

#25 UserProvisionRequest CRD
  deploy/crds/toolchain_v1alpha1_masteruserrecord.yaml
  deploy/crds/toolchain_v1alpha1_userprovisionrequest.yaml
  deploy/role.yaml
  examples/toolchain_v1alpha1_userprovisionrequest_cr.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#26 Create empty UserProvisionRequestController
  go.mod
  go.sum
  pkg/controller/add_userprovisionrequest.go
  pkg/controller/userprovisionrequest/userprovisionrequest_controller.go
Labels: approved, size/L

#28 Add e2e tests make target
  .gitignore
  README.adoc
  build/Dockerfile
  deploy/operator.yaml
  deploy/role_binding.yaml
  make/docker.mk
  make/find-tools.mk
  make/format.mk
  make/go.mk
  make/out.mk
  make/test.mk
  openshift-ci/Dockerfile.deploy
  test/e2e/doc.go
Labels: approved, size/L

#30 upload codecov results
  make/test.mk
Labels: approved, size/M

#31 change due to api make genreate
  deploy/crds/toolchain_v1alpha1_masteruserrecord.yaml
  deploy/crds/toolchain_v1alpha1_usersignup.yaml
Labels: approved, size/S

#33 disable codecov report expiry
  .codecov.yaml
Labels: approved, size/XS

#34 restore missing scripts to build Docker image
  build/bin/entrypoint
  build/bin/user_setup
Labels: approved, lgtm, size/S

#35 fix missing reports on codecov.io
  .codecov.yaml
Labels: approved, size/S

#37 add required permission to fix role issue
  deploy/role.yaml
Labels: approved, lgtm, size/S

#36 update api version
  go.mod
  go.sum
Labels: approved, size/XS

#39 update usersingup/status permission
  deploy/role.yaml
Labels: approved, lgtm, size/XS
