Repository codeready-toolchain/host-operator, pull requests merged in 2019-11, with the labels that each got.

#96 Regenerate manifests by controller-runtime 0.2
  deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
  deploy/crds/toolchain_v1alpha1_nstemplatetier_crd.yaml
  deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_nstemplatetier_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_usersignup_crd.yaml
  hack/deploy_csv.yaml
Labels: approved, size/L

#97 chore: drop 0.0.0 csv template thanks to operator-sdk 0.11.0
  deploy/olm-catalog/toolchain-host-operator/0.0.0/toolchain-host-operator.v0.0.0.clusterserviceversion.yaml
  openshift-ci/Dockerfile.tools
Labels: approved, size/L

#99 Switch to go 1.13 in builder image
  openshift-ci/Dockerfile.tools
Labels: approved, size/S

#100 fix(e2e): install gcc in Dockerfile.tools
  openshift-ci/Dockerfile.tools
Labels: approved, size/XS

#89 add missing permissions on host-operator service account
  deploy/cluster_role.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_usersignup_crd.yaml
  deploy/role.yaml
  hack/deploy_csv.yaml
Labels: approved, size/L

#98 Switch to Kube 1.14
  cmd/manager/main.go
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_usersignup_crd.yaml
  deploy/role.yaml
  go.mod
  go.sum
  hack/deploy_csv.yaml
  pkg/controller/kubefedcluster.go
  pkg/controller/masteruserrecord/masteruserrecord_controller_test.go
  pkg/controller/masteruserrecord/sync_test.go
  pkg/controller/usersignup/usersignup_controller_test.go
  pkg/templates/nstemplatetiers/nstemplatetier_generator_test.go
  tools.go
Labels: approved, size/XL

#102 (DO NOT MERGE) chore: deploy csv for every commit in master via travis-ci
  .travis.yml
  make/docker.mk
Labels: approved, size/M

#94 set 'basic' tiername when creating the MUR
  pkg/controller/usersignup/usersignup_controller.go
  pkg/controller/usersignup/usersignup_controller_test.go
Labels: approved, size/L

#93 Removed CompliantUsername from UserSignup.Spec
  deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
  deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_usersignup_crd.yaml
  go.mod
  go.sum
  hack/deploy_csv.yaml
  pkg/controller/usersignup/usersignup_controller.go
  pkg/controller/usersignup/usersignup_controller_test.go
Labels: approved, size/XL

#104 Add details about cluster for UserAccounts in MUR
  deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
  hack/deploy_csv.yaml
Labels: approved, size/L

#105 chore: add CD status images
  README.adoc
Labels: approved, size/XS

#107 add missing permissions to serviceaccount
  deploy/cluster_role.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  hack/deploy_csv.yaml
Labels: approved, size/M

#106 Add edit role to ns templates
  deploy/templates/nstemplatetiers/advanced-code.yaml
  deploy/templates/nstemplatetiers/advanced-dev.yaml
  deploy/templates/nstemplatetiers/advanced-stage.yaml
  deploy/templates/nstemplatetiers/basic-code.yaml
  deploy/templates/nstemplatetiers/basic-dev.yaml
  deploy/templates/nstemplatetiers/basic-stage.yaml
  pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
Labels: approved, size/L

#103 Add target cluster details to UserAccount Status for MUR
  go.mod
  go.sum
  pkg/apis/apis.go
  pkg/controller/masteruserrecord/masteruserrecord_controller.go
  pkg/controller/masteruserrecord/masteruserrecord_controller_test.go
  pkg/controller/masteruserrecord/sync.go
  pkg/controller/masteruserrecord/sync_test.go
  pkg/controller/usersignup/usersignup_controller_test.go
Labels: approved, size/L

#108 feat(CRT-352): create RegistrationService CRD
  deploy/crds/toolchain_v1alpha1_registrationservice_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_registrationservice_crd.yaml
  examples/toolchain_v1alpha1_registrationservice_cr.yaml
  hack/deploy_csv.yaml
Labels: approved, size/XL

#109 feat(CRT-353): create basic skeleton of RegistrationService controller & update api
  go.mod
  go.sum
  pkg/controller/add_masteruserrecord.go
  pkg/controller/add_usersignup.go
  pkg/controller/controller.go
  pkg/controller/registrationservice/registrationservice_controller.go
Labels: approved, size/L
