Repository codeready-toolchain/host-operator, pull requests merged in 2019-12, with the labels that each got.

#111 chore(CRT-361): copy registration-service deployment and embed it as an asset
  .gitignore
  deploy/registration-service/registration-service.yaml
  make/go.mk
Labels: approved, size/L

#112 Remove deprecated TargetCluster from MUR status
  deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
  go.mod
  go.sum
  hack/deploy_csv.yaml
Labels: approved, size/M

#113 chore: reflect changes in hack resource names
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  hack/deploy_csv.yaml
  hack/install_operator.yaml
Labels: approved, size/M

#115 adding email to usersignup
  deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_usersignup_crd.yaml
  go.mod
  go.sum
  hack/deploy_csv.yaml
Labels: approved, size/S

#116 feat(CRT-358): improve RegistrationService controller so it deploys registration service
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  go.mod
  go.sum
  hack/deploy_csv.yaml
  pkg/controller/registrationservice/registrationservice_controller.go
  pkg/controller/registrationservice/registrationservice_controller_test.go
  pkg/controller/registrationservice/template_test.go
Labels: approved, size/XL

#118 Add Banned property to MasterUserRecord
  deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
  deploy/olm-catalog/host-operator/host-operator.package.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
  hack/deploy_csv.yaml
Labels: approved, size/L

#119 Grant users admin role
  deploy/templates/nstemplatetiers/advanced-code.yaml
  deploy/templates/nstemplatetiers/advanced-dev.yaml
  deploy/templates/nstemplatetiers/advanced-stage.yaml
  deploy/templates/nstemplatetiers/basic-code.yaml
  deploy/templates/nstemplatetiers/basic-dev.yaml
  deploy/templates/nstemplatetiers/basic-stage.yaml
  pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
Labels: approved, size/S

#120 fix: remove the outdated host-operator package file
  deploy/olm-catalog/host-operator/host-operator.package.yaml
Labels: approved, size/XS

#121 Add Deactivated property to UserSignup
  deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_usersignup_crd.yaml
  hack/deploy_csv.yaml
Labels: approved, size/L

#122 Add Che URL to MUR status
  deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
  hack/deploy_csv.yaml
Labels: approved, size/M

#123 Add Che Dashboard URL to MUR status
  go.mod
  go.sum
  pkg/controller/masteruserrecord/sync.go
  pkg/controller/masteruserrecord/sync_test.go
Labels: approved, size/L

#124 Add more permissions to SA
  deploy/cluster_role.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  hack/deploy_csv.yaml
Labels: approved, size/L

#125 Reduce user permissions
  deploy/templates/nstemplatetiers/advanced-code.yaml
  deploy/templates/nstemplatetiers/advanced-dev.yaml
  deploy/templates/nstemplatetiers/advanced-stage.yaml
  deploy/templates/nstemplatetiers/basic-code.yaml
  deploy/templates/nstemplatetiers/basic-dev.yaml
  deploy/templates/nstemplatetiers/basic-stage.yaml
  pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
Labels: approved, size/L
