Repository codeready-toolchain/host-operator, pull requests merged in 2019-08, with the labels that each got.

#38 Add operator deploymentconfig and imagestream for continuous deployment
  deploy/operator_dev_cluster.yaml
  examples/toolchain_v1alpha1_userprovisionrequest_cr.yaml
  make/deploy.mk
  make/dev.mk
Labels: approved, size/L

#42 deploy member-operator for e2e tests
  make/test.mk
Labels: approved, size/M

#44 fix: use scheme with registered types from api repo
  go.mod
  go.sum
  pkg/apis/addtoscheme_toolchain_v1alpha1.go
  pkg/apis/apis.go
Labels: approved, size/S

#45 update operator-sdk v0.10.0
  cmd/manager/main.go
  go.mod
  go.sum
  make/test.mk
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/L

#48 fix: change role to have full permissions for toolchain.dev.openshift.com group
  deploy/role.yaml
Labels: approved, size/S

#47 feat(CRT-165): e2e test for KubeFedCluster controller
  go.mod
  go.sum
  make/test.mk
  test/e2e/kubefedcluster_test.go
  test/e2e/main_test.go
Labels: approved, size/L

#41 feat(CRT-136): create UserAccount in member cluster
  go.mod
  go.sum
  pkg/apis/apis.go
  pkg/controller/masteruserrecord/masteruserrecord_controller.go
  pkg/controller/masteruserrecord/masteruserrecord_controller_test.go
  test/doubles.go
  test/e2e/masteruserrecord_test.go
  test/e2e/wait_util.go
  test/masteruserrecord/assertion.go
  test/masteruserrecord/doubles.go
  test/useraccount/assertion.go
Labels: approved, size/XL

#49 feat: add/modify make targets to clean e2e namespaces
  make/test.mk
Labels: approved, size/S

#51 chore: print logs when e2e tests fail & change variable names
  README.adoc
  make/test.mk
Labels: approved, lgtm, size/M

#53 Add short name for MasterUserRecord
  deploy/crds/toolchain_v1alpha1_masteruserrecord.yaml
  examples/toolchain_v1alpha1_masteruserrecord_cr.yaml
Labels: approved, size/XS

#52 chore: remove vendor support when running operator locally
  README.adoc
  make/dev.mk
Labels: approved, size/XS

#23 feat(CRT-145): sync spec and status between MasterUserRecord and UserAccount
  go.mod
  go.sum
  pkg/controller/masteruserrecord/masteruserrecord_controller.go
  pkg/controller/masteruserrecord/masteruserrecord_controller_test.go
  pkg/controller/masteruserrecord/sync.go
  pkg/controller/masteruserrecord/sync_test.go
  test/e2e/kubefedcluster_test.go
  test/e2e/masteruserrecord_test.go
  test/e2e/wait_util.go
  test/masteruserrecord/assertion.go
  test/masteruserrecord/doubles.go
  test/useraccount/assertion.go
  test/useraccount/doubles.go
Labels: approved, size/XXL

#50 feat(CRT-176): add garbage collection for MasterUserRecord that deletes UserAccounts
  go.mod
  go.sum
  pkg/controller/masteruserrecord/masteruserrecord_controller.go
  pkg/controller/masteruserrecord/masteruserrecord_controller_test.go
  test/e2e/masteruserrecord_test.go
  test/e2e/wait_util.go
  test/masteruserrecord/assertion.go
  test/masteruserrecord/doubles.go
Labels: approved, size/L

#27 Implement automatic user approval and more
  .codecov.yaml
  cmd/manager/main.go
  deploy/crds/toolchain_v1alpha1_usersignup.yaml
  examples/toolchain_v1alpha1_usersignup_cr.yaml
  go.mod
  go.sum
  make/dev.mk
  pkg/config/constants.go
  pkg/controller/masteruserrecord/masteruserrecord_controller_test.go
  pkg/controller/masteruserrecord/sync_test.go
  pkg/controller/usersignup/usersignup_controller.go
  pkg/controller/usersignup/usersignup_controller_test.go
  test/e2e/usersignup_test.go
  test/e2e/wait_util.go
Labels: approved, size/XXL

#54 Update K8s to 1.13.4
  go.mod
  go.sum
Labels: approved

#56 preserve custom fields in CRDs
  deploy/crds/toolchain_v1alpha1_masteruserrecord.yaml
  deploy/crds/toolchain_v1alpha1_usersignup.yaml
Labels: approved, size/M

#57 add gofmt checks for golangci
  .golangci.yml
Labels: approved, size/XS
