Repository codeready-toolchain/host-operator, pull requests merged in 2019-10, with the labels that each got.

#75 chore: add support for Go 1.13
  README.adoc
  go.mod
  go.sum
Labels: approved, size/XS

#73 feat(CRT-227): create CSV for host operator
  deploy/olm-catalog/csv-config.yaml
  deploy/olm-catalog/host-operator/0.0.0/host-operator.v0.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/host-operator/0.0.1/core_v1beta1_kubefedcluster_crd.yaml
  deploy/olm-catalog/host-operator/0.0.1/host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
  deploy/olm-catalog/host-operator/0.0.1/toolchain_v1alpha1_nstemplatetier_crd.yaml
  deploy/olm-catalog/host-operator/0.0.1/toolchain_v1alpha1_usersignup_crd.yaml
  deploy/olm-catalog/host-operator/host-operator.package.yaml
  hack/deploy_csv.yaml
  hack/install_operator.yaml
Labels: approved, size/XXL

#74 Fix make deploy-crd
  make/dev.mk
Labels: approved, size/XS

#76 fixing errors reported by golangci-lint
  pkg/controller/usersignup/usersignup_controller_test.go
Labels: approved, size/S

#68 chore: install newer git and allow unrelated histories while merging
  make/test.mk
  openshift-ci/Dockerfile.tools
Labels: approved, size/S

#69 generate YAML manifests for NSTemplateTier resources
  .gitignore
  .golangci.yml
  deploy/templates/nstemplatetiers/advanced-code.yaml
  deploy/templates/nstemplatetiers/advanced-dev.yaml
  deploy/templates/nstemplatetiers/advanced-stage.yaml
  deploy/templates/nstemplatetiers/basic-code.yaml
  deploy/templates/nstemplatetiers/basic-dev.yaml
  deploy/templates/nstemplatetiers/basic-stage.yaml
  go.mod
  go.sum
  make/clean.mk
  make/find-tools.mk
  make/go.mk
  pkg/apis/apis.go
  pkg/templates/nstemplatetiers/nstemplatetier_generator.go
  pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
  pkg/templates/templates_test.go
  test/templates/nstemplatetiers/README.adoc
  test/templates/nstemplatetiers/advanced-code.yaml
  test/templates/nstemplatetiers/advanced-dev.yaml
  test/templates/nstemplatetiers/advanced-stage.yaml
  test/templates/nstemplatetiers/basic-code.yaml
  test/templates/nstemplatetiers/basic-dev.yaml
  test/templates/nstemplatetiers/basic-stage.yaml
  test/templates/nstemplatetiers/metadata.yaml
Labels: approved, size/XL

#72 chore(CRT-229): add targets that help with deploying/installing operator
  README.adoc
  make/dev.mk
  make/docker.mk
Labels: approved, size/L

#79 Add 'tier' as short name for NSTemplateTier CRD
  deploy/crds/toolchain_v1alpha1_nstemplatetier_crd.yaml
  deploy/olm-catalog/host-operator/0.0.1/host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/host-operator/0.0.1/toolchain_v1alpha1_nstemplatetier_crd.yaml
  hack/deploy_csv.yaml
Labels: approved, size/S

#80 add commit and buildtime vars
  cmd/manager/main.go
  cmd/manager/main_test.go
  go.sum
Labels: approved, size/S

#81 fix: check the remote branch correctly and don't commit while merging
  make/test.mk
Labels: approved, size/XS

#83 Exclude cmd/manager (main) from coverage report
  .codecov.yaml
  make/test.mk
Labels: approved, size/XS

#78 create/update NSTemplateTiers at controller startup
  cmd/manager/main.go
  go.sum
  pkg/templates/nstemplatetiers/nstemplatetier_generator.go
  pkg/templates/nstemplatetiers/nstemplatetier_generator_test.go
  pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
Labels: approved, size/L

#82 update CRDs with extra annotations, generated with go 1.13
  deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
  deploy/crds/toolchain_v1alpha1_nstemplatetier_crd.yaml
  deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
  deploy/olm-catalog/host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
  deploy/olm-catalog/host-operator/0.0.1/toolchain_v1alpha1_nstemplatetier_crd.yaml
  deploy/olm-catalog/host-operator/0.0.1/toolchain_v1alpha1_usersignup_crd.yaml
  hack/deploy_csv.yaml
Labels: approved, size/M

#77 chore(CRT-281): create KubeFedCluster CRD programmatically
  cmd/manager/main.go
  deploy/cluster_role.yaml
  deploy/crds/core_v1beta1_kubefedcluster_crd.yaml
  deploy/olm-catalog/host-operator/0.0.0/host-operator.v0.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/host-operator/0.0.1/core_v1beta1_kubefedcluster_crd.yaml
  deploy/olm-catalog/host-operator/0.0.1/host-operator.v0.0.1.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/deploy_csv.yaml
  pkg/controller/kubefedcluster.go
  tools.go
Labels: approved, size/L

#85 fix: create KubeFedCluster CRD before client and cache are started
  cmd/manager/main.go
  deploy/olm-catalog/host-operator/0.0.0/host-operator.v0.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/host-operator/0.0.1/host-operator.v0.0.1.clusterserviceversion.yaml
  hack/deploy_csv.yaml
  pkg/controller/kubefedcluster.go
Labels: approved, lgtm, size/M

#84 Generated updated CRD for UserSignup.CompliantUserName
  deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
  deploy/olm-catalog/host-operator/0.0.1/host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/host-operator/0.0.1/toolchain_v1alpha1_usersignup_crd.yaml
  examples/toolchain_v1alpha1_usersignup_cr.yaml
  go.mod
  go.sum
  hack/deploy_csv.yaml
  pkg/controller/usersignup/usersignup_controller_test.go
Labels: approved, size/L

#88 configure golangci-lint timeout
  .golangci.yml
  make/lint.mk
Labels: approved, size/XS

#87 refactor Commit and BuildTime variables
  .dockerignore
  cmd/manager/main.go
  make/go.mk
  version/version.go
  version/version_test.go
Labels: approved, size/M

#86 support commit hashes as numbers
  make/go.mk
  pkg/templates/nstemplatetiers/nstemplatetier_generator.go
  pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
  test/templates/nstemplatetiers/metadata.yaml
Labels: approved, size/M

#90 Remove UserID from UserSignup.Spec
  deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
  deploy/olm-catalog/host-operator/0.0.1/toolchain_v1alpha1_usersignup_crd.yaml
  examples/toolchain_v1alpha1_usersignup_cr.yaml
  hack/deploy_csv.yaml
Labels: approved, size/S

#91 Updated host operator to remove UserSignup.Spec.UserID
  go.mod
  go.sum
  pkg/controller/usersignup/usersignup_controller.go
  pkg/controller/usersignup/usersignup_controller_test.go
Labels: approved, size/L

#95 chore(CRT-331): rename host-operator to toolchain-host-operator
  deploy/olm-catalog/host-operator/host-operator.package.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.0/toolchain-host-operator.v0.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_nstemplatetier_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_usersignup_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/toolchain-host-operator.package.yaml
  hack/deploy_csv.yaml
  hack/install_operator.yaml
Labels: approved, size/M
