Repository codeready-toolchain/host-operator, pull requests merged in 2019-06, with the labels that each got.

#6 Add resourceVersion to MasterUserRecord status
  deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
  examples/toolchain_v1alpha1_masteruserrecord_cr.yaml
Labels: approved, size/M

#8 Add freshly generated MasterUserRecordController
  README.adoc
  go.mod
  go.sum
  pkg/controller/add_masteruserrecord.go
  pkg/controller/masteruserrecord/masteruserrecord_controller.go
Labels: approved, size/L

#9 fix - no kind is registered error while starting host operator locally
  examples/toolchain_v1alpha1_masteruserrecord_cr.yaml
  examples/toolchain_v1alpha1_nstemplatetier_cr.yaml
  pkg/apis/addtoscheme_toolchain_v1alpha1.go
Labels: approved, lgtm, size/S

#10 Rename CRD files to align with api generator
  deploy/crds/toolchain_v1alpha1_masteruserrecord.yaml
  deploy/crds/toolchain_v1alpha1_nstemplatetier.yaml
Labels: approved, lgtm, size/M

#11 fix: add toolchain.dev.openshift.com group to host-operator role
  deploy/role.yaml
Labels: approved, size/XS

#12 Add UserID to MasterUserRecord
  deploy/crds/toolchain_v1alpha1_masteruserrecord.yaml
  examples/toolchain_v1alpha1_masteruserrecord_cr.yaml
Labels: approved, lgtm, size/S

#13 feat(CRT-144): Add KubeFedCluster CRD & controller
  Makefile
  README.adoc
  cmd/manager/main.go
  deploy/crds/core_v1beta1_kubefedcluster.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  go.mod
  go.sum
  make/dev.mk
  pkg/controller/add_kubefedcluster.go
  pkg/controller/controller.go
Labels: approved, lgtm, size/XL

#15 correct crd file name
  make/dev.mk
Labels: approved, lgtm, size/XS

#17 fix: exclude vendor dir from files to be formatted
  gofmt_exclude
  make/format.mk
Labels: approved, lgtm, size/XS

#16 setup Codecov and cleanup Makefile(s)
  .codecov.yaml
  .yamllint
  Makefile
  README.adoc
  go.mod
  go.sum
  make/dev.mk
  make/find-tools.mk
  make/format.mk
  make/git.mk
  make/go.mk
  make/help.mk
  make/lint.mk
  make/out.mk
  make/test.mk
  make/verbose.mk
Labels: approved, size/L

#19 change to toolchain-common
  .gitignore
  README.adoc
  make/dev.mk
Labels: approved, size/S

#14 feat(CRT-150): add caching controller for KubeFedCluster
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/controller/controller.go
  pkg/controller/kubefedcluster.go
Labels: approved, size/L

#20 Rename ResourceVersion to SyncIndex in MasterUserRecord
  deploy/crds/toolchain_v1alpha1_masteruserrecord.yaml
  examples/toolchain_v1alpha1_masteruserrecord_cr.yaml
Labels: approved, size/S

#21 Rename Status.ResourceVersion to SyncIndex in MasterUserRecord
  deploy/crds/toolchain_v1alpha1_masteruserrecord.yaml
Labels: approved, size/S

#22 separate goal to upload codecov report
  make/test.mk
Labels: approved, size/M
