Repository codeready-toolchain/host-operator, pull requests merged in 2020-01, with the labels that each got.

#127 Permission error in host
  deploy/cluster_role.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  hack/deploy_csv.yaml
Labels: approved, size/L

#130 fix: use toolchain apis for listing CRs to be monitored
  cmd/manager/main.go
Labels: approved, size/XS

#131 chore: update api repo to use openshift/api@release-4.2
  go.mod
  go.sum
Labels: approved, size/S

#132 fix: common api sheme contain only CRs
  go.mod
  go.sum
  pkg/apis/apis.go
Labels: approved, size/S

#133 chore: remove unneeded permissons
  deploy/cluster_role.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  hack/deploy_csv.yaml
Labels: approved, size/L

#134 Regenerated from api - added BannedUser type
  deploy/crds/toolchain_v1alpha1_banneduser_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_banneduser_crd.yaml
  examples/toolchain_v1alpha1_banneduser_cr.yaml
  hack/deploy_csv.yaml
Labels: approved, size/L

#135 fix: propagate BannedUser into deploy hack file & regenerate base CSV
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  hack/deploy_csv.yaml
Labels: approved, size/M

#137 chore: install github.com/kislyuk/yq binary
  .travis.yml
  openshift-ci/Dockerfile.tools
Labels: approved, size/XS

#136 feat(CRT-363): load reg-service params from config files
  cmd/manager/main.go
  deploy/env/dev.yaml
  deploy/env/e2e-tests.yaml
  deploy/env/prod.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  hack/deploy_csv.yaml
  make/dev.mk
  pkg/config/constants.go
  pkg/configuration/configuration.go
  pkg/configuration/configuration_test.go
  pkg/controller/usersignup/usersignup_controller.go
  pkg/controller/usersignup/usersignup_controller_test.go
Labels: approved, size/XL

#138 feat: store reg-service parameters in a map
  deploy/crds/toolchain_v1alpha1_registrationservice_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_registrationservice_crd.yaml
  examples/toolchain_v1alpha1_registrationservice_cr.yaml
  go.mod
  go.sum
  hack/deploy_csv.yaml
  pkg/controller/registrationservice/registrationservice_controller.go
  pkg/controller/registrationservice/registrationservice_controller_test.go
  pkg/controller/registrationservice/template_test.go
Labels: approved, size/L

#139 feat: select first member cluster ready and with capacity
  go.mod
  go.sum
  pkg/controller/usersignup/usersignup_controller.go
  pkg/controller/usersignup/usersignup_controller_test.go
Labels: approved, size/L

#126 Support user deactivation in UserSignup controller
  go.sum
  pkg/controller/usersignup/usersignup_controller.go
  pkg/controller/usersignup/usersignup_controller_test.go
Labels: approved, size/L

#140 chore(CRT-362): use registration-service as embedded repo in CD
  .travis.yml
Labels: approved, size/XS

#117 feat(CRT-354): create RegistrationService CR during the operator startup
  cmd/manager/main.go
  deploy/env/dev.yaml
  deploy/env/e2e-tests.yaml
  pkg/controller/registrationservice/creation.go
  pkg/controller/registrationservice/creation_test.go
  pkg/controller/registrationservice/registrationservice_controller_test.go
  test/registrationservice.go
Labels: approved, size/L

#141 Fix MUR status synchronization in case of target availability error
  pkg/controller/masteruserrecord/masteruserrecord_controller_test.go
  pkg/controller/masteruserrecord/sync.go
Labels: approved, size/L
