Repository codeready-toolchain/host-operator, pull requests merged in 2020-02, with the labels that each got.

#143 generated from make generate in api
  deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
  hack/deploy_csv.yaml
Labels: approved, size/L

#144 chore: add push-to-quay-nightly makefile target & add courier to dockerfile
  .travis.yml
  make/manifests.mk
  openshift-ci/Dockerfile.tools
Labels: approved, size/S

#145 chore: add generate-olm-files make target
  README.adoc
  hack/deploy_csv.yaml
  make/manifests.mk
Labels: approved, size/M

#146 Synchronizespec compare fields
  go.mod
  go.sum
  pkg/controller/masteruserrecord/masteruserrecord_controller.go
  pkg/controller/masteruserrecord/masteruserrecord_controller_test.go
  pkg/controller/masteruserrecord/sync.go
  pkg/controller/masteruserrecord/sync_test.go
  pkg/controller/registrationservice/creation.go
  pkg/controller/registrationservice/creation_test.go
  pkg/controller/registrationservice/registrationservice_controller.go
  pkg/controller/registrationservice/registrationservice_controller_test.go
  pkg/controller/usersignup/usersignup_controller.go
  pkg/controller/usersignup/usersignup_controller_test.go
Labels: approved, size/L

#147 Delete deprecated API
  deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
  go.mod
  go.sum
  hack/deploy_csv.yaml
  pkg/controller/masteruserrecord/masteruserrecord_controller.go
  pkg/controller/masteruserrecord/sync.go
  pkg/controller/usersignup/usersignup_controller.go
  pkg/controller/usersignup/usersignup_controller_test.go
Labels: approved, size/L

#148 Update to Kube 1.16.2
  README.adoc
  deploy/crds/toolchain_v1alpha1_banneduser_crd.yaml
  deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
  deploy/crds/toolchain_v1alpha1_nstemplatetier_crd.yaml
  deploy/crds/toolchain_v1alpha1_registrationservice_crd.yaml
  deploy/crds/toolchain_v1alpha1_usersignup_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_banneduser_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_nstemplatetier_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_registrationservice_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_usersignup_crd.yaml
  go.mod
  go.sum
  hack/deploy_csv.yaml
Labels: approved, size/XXL

#151 Add get/list bannedusers to reg-service SA
  deploy/registration-service/registration-service.yaml
Labels: approved, size/XS
