Repository codeready-toolchain/host-operator, pull requests merged in 2020-03, with the labels that each got.

#153 moving reaosns to api
  go.mod
  go.sum
  pkg/controller/registrationservice/registrationservice_controller.go
Labels: approved, size/S

#154 using reasons from api
  go.mod
  go.sum
  pkg/controller/usersignup/usersignup_controller.go
Labels: approved, size/M

#149 Disabling useraccount
  go.mod
  go.sum
  pkg/controller/masteruserrecord/masteruserrecord_controller.go
  pkg/controller/masteruserrecord/masteruserrecord_controller_test.go
  pkg/controller/masteruserrecord/sync.go
  pkg/controller/masteruserrecord/sync_test.go
Labels: approved, size/L

#155 chore(CRT-478): create ChangeTierRequest that will ensure tier change
  deploy/crds/toolchain_v1alpha1_changetierrequest_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_changetierrequest_crd.yaml
  examples/toolchain_v1alpha1_changetierrequest_cr.yaml
  hack/deploy_csv.yaml
Labels: approved, size/L

#156 add ClusterResourceQuota template+revision in NSTemplateTier CR
  deploy/crds/toolchain_v1alpha1_nstemplatetier_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_nstemplatetier_crd.yaml
  hack/deploy_csv.yaml
Labels: approved, size/L

#158 chore: generate basic scaffolding of changetierrequest controller
  go.mod
  go.sum
  pkg/controller/changetierrequest/changetierrequest_controller.go
  pkg/controller/controller.go
Labels: approved, size/M

#152 chore(CRT-475): add team tier
  deploy/templates/nstemplatetiers/team-dev.yaml
  deploy/templates/nstemplatetiers/team-stage.yaml
  pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
Labels: approved, size/L

#161 add cluster-scoped resources in NSTemplateTiers
  .gitignore
  cmd/manager/main.go
  deploy/templates/nstemplatetiers/advanced/cluster.yaml
  deploy/templates/nstemplatetiers/advanced/ns_code.yaml
  deploy/templates/nstemplatetiers/advanced/ns_dev.yaml
  deploy/templates/nstemplatetiers/advanced/ns_stage.yaml
  deploy/templates/nstemplatetiers/basic/cluster.yaml
  deploy/templates/nstemplatetiers/basic/ns_code.yaml
  deploy/templates/nstemplatetiers/basic/ns_dev.yaml
  deploy/templates/nstemplatetiers/basic/ns_stage.yaml
  deploy/templates/nstemplatetiers/team/cluster.yaml
  deploy/templates/nstemplatetiers/team/ns_dev.yaml
  deploy/templates/nstemplatetiers/team/ns_stage.yaml
  go.mod
  go.sum
  make/go.mk
  pkg/controller/registrationservice/registrationservice_controller.go
  pkg/templates/nstemplatetiers/nstemplatetier_binassets.go
  pkg/templates/nstemplatetiers/nstemplatetier_generator.go
  pkg/templates/nstemplatetiers/nstemplatetier_generator_test.go
  pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
  test/templates/nstemplatetiers/README.adoc
  test/templates/nstemplatetiers/advanced/cluster.yaml
  test/templates/nstemplatetiers/advanced/ns_code.yaml
  test/templates/nstemplatetiers/advanced/ns_dev.yaml
  test/templates/nstemplatetiers/advanced/ns_stage.yaml
  test/templates/nstemplatetiers/basic/cluster.yaml
  test/templates/nstemplatetiers/basic/ns_code.yaml
  test/templates/nstemplatetiers/basic/ns_dev.yaml
  test/templates/nstemplatetiers/basic/ns_stage.yaml
  test/templates/nstemplatetiers/doc.go
  test/templates/nstemplatetiers/metadata.yaml
  test/templates/nstemplatetiers/nocluster/ns_code.yaml
  test/templates/nstemplatetiers/nocluster/ns_dev.yaml
  test/templates/nstemplatetiers/nocluster/ns_stage.yaml
  test/templates/nstemplatetiers/team/cluster.yaml
  test/templates/nstemplatetiers/team/ns_dev.yaml
  test/templates/nstemplatetiers/team/ns_stage.yaml
Labels: approved, size/XXL

#159 add 'clusterResources' field in NSTemplateSet
  deploy/crds/toolchain_v1alpha1_masteruserrecord_crd.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_masteruserrecord_crd.yaml
  hack/deploy_csv.yaml
Labels: approved, size/XXL

#162 chore: remove unused Viper instances
  go.mod
  go.sum
  pkg/configuration/configuration.go
  pkg/configuration/configuration_test.go
Labels: approved

#142 Implement ban user logic in UserSignupController
  go.mod
  go.sum
  pkg/controller/registrationservice/registrationservice_controller_test.go
  pkg/controller/usersignup/usersignup_controller.go
  pkg/controller/usersignup/usersignup_controller_test.go
Labels: approved, size/XL

#160 feat(CRT-478): modify ChangeTierRequest_controller to change tier baseded on request
  cmd/manager/main.go
  deploy/env/e2e-tests.yaml
  go.mod
  pkg/configuration/configuration.go
  pkg/configuration/configuration_test.go
  pkg/controller/changetierrequest/changetierrequest_controller.go
  pkg/controller/changetierrequest/changetierrequest_controller_test.go
  pkg/controller/controller.go
  pkg/controller/masteruserrecord/masteruserrecord_controller.go
  pkg/controller/registrationservice/registrationservice_controller.go
  pkg/controller/usersignup/usersignup_controller.go
Labels: approved, size/XL

#163 add limit ranges on namespace templates
  deploy/templates/nstemplatetiers/advanced/cluster.yaml
  deploy/templates/nstemplatetiers/advanced/ns_code.yaml
  deploy/templates/nstemplatetiers/advanced/ns_dev.yaml
  deploy/templates/nstemplatetiers/advanced/ns_stage.yaml
  deploy/templates/nstemplatetiers/basic/cluster.yaml
  deploy/templates/nstemplatetiers/basic/ns_code.yaml
  deploy/templates/nstemplatetiers/basic/ns_dev.yaml
  deploy/templates/nstemplatetiers/basic/ns_stage.yaml
  deploy/templates/nstemplatetiers/team/cluster.yaml
  deploy/templates/nstemplatetiers/team/ns_dev.yaml
  deploy/templates/nstemplatetiers/team/ns_stage.yaml
  hack/deploy_csv.yaml
  pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
  test/templates/nstemplatetiers/advanced/ns_code.yaml
  test/templates/nstemplatetiers/advanced/ns_dev.yaml
  test/templates/nstemplatetiers/advanced/ns_stage.yaml
  test/templates/nstemplatetiers/basic/ns_code.yaml
  test/templates/nstemplatetiers/basic/ns_dev.yaml
  test/templates/nstemplatetiers/basic/ns_stage.yaml
  test/templates/nstemplatetiers/nocluster/ns_code.yaml
  test/templates/nstemplatetiers/nocluster/ns_dev.yaml
  test/templates/nstemplatetiers/nocluster/ns_stage.yaml
  test/templates/nstemplatetiers/team/ns_dev.yaml
  test/templates/nstemplatetiers/team/ns_stage.yaml
Labels: approved

#164 Isolate pods in user namespaces
  deploy/templates/nstemplatetiers/advanced/ns_code.yaml
  deploy/templates/nstemplatetiers/advanced/ns_dev.yaml
  deploy/templates/nstemplatetiers/advanced/ns_stage.yaml
  deploy/templates/nstemplatetiers/basic/ns_code.yaml
  deploy/templates/nstemplatetiers/basic/ns_dev.yaml
  deploy/templates/nstemplatetiers/basic/ns_stage.yaml
  deploy/templates/nstemplatetiers/team/ns_dev.yaml
  deploy/templates/nstemplatetiers/team/ns_stage.yaml
  pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
Labels: approved

#165 Code cleanup
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  examples/toolchain_v1alpha1_usersignup_cr.yaml
  go.mod
  go.sum
  hack/deploy_csv.yaml
  pkg/controller/masteruserrecord/masteruserrecord_controller.go
  pkg/controller/masteruserrecord/masteruserrecord_controller_test.go
  pkg/controller/masteruserrecord/sync.go
  pkg/controller/masteruserrecord/sync_test.go
  pkg/controller/usersignup/usersignup_controller.go
  pkg/controller/usersignup/usersignup_controller_test.go
Labels: approved

#166 chore: rename toolchain-*-edit role to rbac-edit
  deploy/templates/nstemplatetiers/advanced/ns_code.yaml
  deploy/templates/nstemplatetiers/basic/ns_code.yaml
  deploy/templates/nstemplatetiers/team/ns_dev.yaml
  deploy/templates/nstemplatetiers/team/ns_stage.yaml
  pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
Labels: approved

#169 chore: use registry URL in new CI cluster
  make/test.mk
Labels: approved

#168 fix: log.Info should not take odd number of parameters
  pkg/controller/changetierrequest/changetierrequest_controller.go
Labels: approved

#150 Update operator-sdk to 0.15.2
  .travis.yml
  README.adoc
  deploy/crds/toolchain_v1alpha1_changetierrequest_crd.yaml
  deploy/olm-catalog/csv-config.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain-host-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/toolchain-host-operator/0.0.1/toolchain_v1alpha1_changetierrequest_crd.yaml
  examples/toolchain_v1alpha1_usersignup_cr.yaml
  go.mod
  go.sum
  hack/deploy_csv.yaml
  openshift-ci/Dockerfile.tools
Labels: approved, size/M

#170 Fix operator-sdk key
  .travis.yml
  go.mod
  go.sum
  openshift-ci/Dockerfile.tools
Labels: approved
