Repository codeready-toolchain/host-operator, pull requests merged in 2022-06, with the labels that each got.

#645 Disable Idler for appstudio tier
  deploy/templates/nstemplatetiers/appstudio/cluster.yaml
Labels: approved

#646 Allow appstudio users create configmaps
  deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
Labels: approved, ok-to-test

#647 Fix encoding of usernames with invalid end chars
  controllers/usersignup/usersignup_controller.go
  controllers/usersignup/usersignup_controller_test.go
Labels: approved

#644 refactor UserSignupController: do not watch SpaceBindings
  controllers/space/space_controller.go
  controllers/space/space_controller_test.go
  controllers/usersignup/spacebinding.go
  controllers/usersignup/usersignup_controller.go
Labels: approved

#642 Migrate to user tier
  controllers/changetierrequest/changetierrequest_controller.go
  controllers/changetierrequest/changetierrequest_controller_test.go
  controllers/deactivation/deactivation_controller_test.go
  controllers/masteruserrecord/masteruserrecord_controller_test.go
  controllers/masteruserrecord/sync_test.go
  controllers/toolchainconfig/configuration.go
  controllers/toolchainconfig/configuration_test.go
  controllers/usersignup/masteruserrecord.go
  controllers/usersignup/masteruserrecord_test.go
  controllers/usersignup/spacebinding_test.go
  controllers/usersignup/status.go
  controllers/usersignup/usersignup_controller.go
  controllers/usersignup/usersignup_controller_test.go
  go.mod
  go.sum
  main.go
Labels: approved

#643 Generated files after removal of TUR CRD
  PROJECT
  config/crd/bases/toolchain.dev.openshift.com_nstemplatetiers.yaml
  config/crd/bases/toolchain.dev.openshift.com_templateupdaterequests.yaml
  config/crd/kustomization.yaml
  config/manifests/bases/host-operator.clusterserviceversion.yaml
  go.mod
  go.sum
Labels: approved

#651 Generated files for MemberOperatorConfig update
  config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml
Labels: approved

#654 fix: update api to support skipUserCreation param
  go.mod
  go.sum
Labels: approved, lgtm

#656 refactor: avoid flaky cases during usersignup migration
  controllers/usersignup/predicate.go
  controllers/usersignup/predicate_test.go
  controllers/usersignup/usersignup_controller.go
Labels: approved

#624 feat: SocialEvent controller
  config/crd/bases/toolchain.dev.openshift.com_socialevents.yaml
  controllers/socialevent/socialevent_controller.go
  controllers/socialevent/socialevent_controller_test.go
  controllers/socialevent/status_updater.go
  controllers/socialevent/status_updater_test.go
  controllers/usersignup/status_updater.go
  controllers/usersignup/status_updater_test.go
  go.mod
  go.sum
  main.go
  test/socialevent/socialevent.go
  test/socialevent/socialevent_assertion.go
Labels: approved

#652 Remove user tier migration code now that migration is complete
  controllers/deactivation/deactivation_controller.go
  controllers/deactivation/deactivation_controller_test.go
  controllers/usersignup/masteruserrecord.go
  controllers/usersignup/masteruserrecord_test.go
  controllers/usersignup/usersignup_controller_test.go
Labels: approved

#661 Allow appstudio users to create Environment APIs
  deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
Labels: approved, ok-to-test

#657 appstudio: increase deploy memory quota
  deploy/templates/nstemplatetiers/appstudio/ns_appstudio.yaml
Labels: approved

#662 move the namespace name to subject of idler notification
  deploy/templates/notificationtemplates/idlertriggered/notification.html
  deploy/templates/notificationtemplates/idlertriggered/subject.txt
  pkg/templates/notificationtemplates/notification_generator_test.go
Labels: approved

#659 feat: update SocialEvent when users signup
  controllers/socialevent/predicate.go
  controllers/socialevent/socialevent_controller.go
  controllers/socialevent/socialevent_controller_test.go
  controllers/socialevent/status_updater_test.go
  go.mod
  go.sum
  main.go
  test/socialevent/socialevent.go
  test/socialevent/socialevent_assertion.go
Labels: approved
