Repository codeready-toolchain/host-operator, pull requests merged in 2022-10, with the labels that each got.

#687 refactor: use func to compute hash from toolchain-common
  controllers/deactivation/deactivation_controller_test.go
  controllers/nstemplatetier/util/hash.go
  controllers/usersignup/usersignup_controller.go
Labels: approved

#694 Add crtadmin roles into test-tier
  deploy/templates/nstemplatetiers/test/ns_dev.yaml
Labels: approved, lgtm, ok-to-test

#693 Update base1ns with new resource quotas from test tier.
  deploy/templates/nstemplatetiers/base1ns/cluster.yaml
  deploy/templates/nstemplatetiers/base1ns/ns_dev.yaml
  deploy/templates/nstemplatetiers/base1ns/spacerole_admin.yaml
Labels: approved, ok-to-test

#690 build: upgrade Go 1.17 and k8s.io v0.23.5
  .github/workflows/ci-build.yml
  .github/workflows/operator-cd.yml
  .github/workflows/publish-operators-for-e2e-tests.yml
  README.adoc
  go.mod
  go.sum
  make/get-tool.mk
  make/go.mk
  openshift-ci/Dockerfile.tools
Labels: approved

#689 Remove migration code and tests
  controllers/usersignup/predicate.go
  controllers/usersignup/predicate_test.go
  controllers/usersignup/status_updater.go
  controllers/usersignup/usersignup_controller.go
  controllers/usersignup/usersignup_controller_test.go
Labels: approved

#699 Add new base tier with 6 day idler
  deploy/templates/nstemplatetiers/base1ns6didler/based_on_tier.yaml
  pkg/templates/nstemplatetiers/nstemplatetier_generator_whitebox_test.go
Labels: approved
