Repository codeready-toolchain/host-operator, pull requests merged in 2023-05, with the labels that each got.

#789 feat: Implement "copy secret" functionality in SpaceRequest controller
  controllers/spacerequest/spacerequest_controller.go
  controllers/spacerequest/spacerequest_controller_test.go
  go.mod
  go.sum
  main.go
  pkg/cluster/cluster.go
  test/space/space.go
  test/spacerequest/spacerequest.go
  test/spacerequest/spacerequest_assertions.go
Labels: approved

#799 Names product; adds private preview notification
  deploy/templates/notificationtemplates/appstudio/idlertriggered/notification.html
  deploy/templates/notificationtemplates/appstudio/userdeactivated/notification.html
  deploy/templates/notificationtemplates/appstudio/userdeactivating/notification.html
  deploy/templates/notificationtemplates/appstudio/userprovisioned/notification.html
  deploy/templates/notificationtemplates/appstudio/userprovisioned/subject.txt
  pkg/templates/notificationtemplates/notification_generator_test.go
Labels: approved, lgtm, ok-to-test

#790 Increase cpu request quota to 3 CPU
  deploy/templates/nstemplatetiers/base1ns/ns_dev.yaml
Labels: approved, ok-to-test

#792 fix: Don't block Space deletion if it hasn't been provisiond to member cluster yet
  controllers/space/space_controller.go
  controllers/space/space_controller_test.go
Labels: approved

#795 fix: rename MapToSubSpacesByParentObjectName and improve comment
  controllers/space/mapper.go
  controllers/space/mapper_test.go
  controllers/space/space_controller.go
Labels: approved

#794 shorten compliant username
  controllers/usersignup/usersignup_controller.go
  controllers/usersignup/usersignup_controller_test.go
  go.mod
  go.sum
  test/usersignup_assertions.go
Labels: approved

#797 Add a dedicated service account to run Tekton pipelines
  deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml
Labels: approved, ok-to-test

#801 fix: rename USERNAME template parameter with SPACE_NAME
  deploy/templates/nstemplatetiers/appstudio-env/cluster.yaml
  deploy/templates/nstemplatetiers/appstudio-env/ns_env.yaml
  deploy/templates/nstemplatetiers/appstudio/cluster.yaml
  deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml
  deploy/templates/nstemplatetiers/base/cluster.yaml
  deploy/templates/nstemplatetiers/base/ns_dev.yaml
  deploy/templates/nstemplatetiers/base/ns_stage.yaml
  deploy/templates/nstemplatetiers/base1ns/cluster.yaml
  deploy/templates/nstemplatetiers/base1ns/ns_dev.yaml
  deploy/templates/nstemplatetiers/test/cluster.yaml
  deploy/templates/nstemplatetiers/test/ns_dev.yaml
  test/templates/nstemplatetiers/appstudio/cluster.yaml
  test/templates/nstemplatetiers/appstudio/ns_tenant.yaml
  test/templates/nstemplatetiers/base/cluster.yaml
  test/templates/nstemplatetiers/base/ns_dev.yaml
  test/templates/nstemplatetiers/base/ns_stage.yaml
  test/templates/nstemplatetiers/nocluster/ns_dev.yaml
  test/templates/nstemplatetiers/nocluster/ns_stage.yaml
Labels: approved

#802 Update docs link in app studio welcome email
  deploy/templates/notificationtemplates/appstudio/userprovisioned/notification.html
Labels: approved, lgtm, ok-to-test

#803 Add "community" on line 56
  deploy/templates/notificationtemplates/appstudio/userprovisioned/notification.html
Labels: approved, lgtm, ok-to-test

#798 Added workspace_name label in namespace template
  deploy/templates/nstemplatetiers/appstudio-env/ns_env.yaml
  deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml
  test/templates/nstemplatetiers/appstudio/ns_tenant.yaml
Labels: approved, ok-to-test

#804 Add approved metric that includes method of approval
  controllers/usersignup/usersignup_controller.go
  controllers/usersignup/usersignup_controller_test.go
  pkg/metrics/metrics.go
Labels: approved

#807 appstudio: add RHTAP to emails
  deploy/templates/notificationtemplates/appstudio/userdeactivated/notification.html
  deploy/templates/notificationtemplates/appstudio/userdeactivated/subject.txt
  deploy/templates/notificationtemplates/appstudio/userdeactivating/notification.html
  deploy/templates/notificationtemplates/appstudio/userdeactivating/subject.txt
  deploy/templates/notificationtemplates/appstudio/userprovisioned/notification.html
  pkg/templates/notificationtemplates/notification_generator_test.go
Labels: approved, lgtm

#808 Add UserSignupVerificationRequiredTotal metric
  controllers/usersignup/usersignup_controller.go
  controllers/usersignup/usersignup_controller_test.go
  pkg/metrics/metrics.go
Labels: approved

#806 separate devSpaces analytics
  config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml
Labels: approved

#810 fix: ldflags commit id and build time in github
  make/go.mk
Labels: approved

#812 Change memory limit for build workloads
  deploy/templates/nstemplatetiers/base1ns/ns_dev.yaml
Labels: approved

#813 Remove woopra
  config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml
Labels: approved

#811 Move to the new name of the tekton sa
  deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
Labels: approved, ok-to-test
