Repository codeready-toolchain/host-operator, pull requests merged in 2023-10, with the labels that each got.

#874 Network policy for cnv
  deploy/templates/nstemplatetiers/base/ns_dev.yaml
  deploy/templates/nstemplatetiers/base/ns_stage.yaml
  deploy/templates/nstemplatetiers/base1ns/ns_dev.yaml
Labels: approved

#875 fix: forward context in ToolchainConfig controller
  controllers/toolchainconfig/toolchainconfig_controller.go
  controllers/toolchainconfig/toolchainconfig_controller_test.go
Labels: approved, lgtm, ok-to-test

#873 fix: forward context in ToolchainStatus controller
  controllers/toolchainstatus/toolchainstatus_controller.go
Labels: approved, lgtm, ok-to-test

#869 fix: forward context in UserSignup controller
  controllers/usersignup/status_updater.go
  controllers/usersignup/status_updater_test.go
  controllers/usersignup/usersignup_controller.go
Labels: approved, lgtm, ok-to-test

#877 fix: forward context in SpaceRequest controller
  controllers/spacerequest/spacerequest_controller.go
Labels: approved, lgtm, ok-to-test

#870 SANDBOX-202: Differentiation between notification emails from different environments
  controllers/toolchainstatus/toolchainstatus_controller.go
  controllers/toolchainstatus/toolchainstatus_controller_test.go
Labels: approved, ok-to-test

#879 ci: bump actions to silence node12 warnings
  .github/workflows/ci-build.yml
  .github/workflows/ci-check-gomod.yml
  .github/workflows/operator-cd.yml
  .github/workflows/publish-operators-for-e2e-tests.yml
Labels: approved, lgtm, ok-to-test

#876 Allow user signups to complete when the associated space is updating
  controllers/usersignup/usersignup_controller.go
  controllers/usersignup/usersignup_controller_test.go
Labels: approved, lgtm, ok-to-test

#880 Synchronize propagated claims when updated in UserSignup
  controllers/masteruserrecord/masteruserrecord_controller_test.go
  controllers/masteruserrecord/sync.go
  controllers/usersignup/masteruserrecord.go
  controllers/usersignup/usersignup_controller_test.go
  go.mod
  go.sum
Labels: approved

#882 update notification just containing cluster domain name
  controllers/toolchainstatus/toolchainstatus_controller.go
  controllers/toolchainstatus/toolchainstatus_controller_test.go
Labels: approved, ok-to-test

#881 Do not try to delete UserSignups multiple times
  controllers/usersignupcleanup/usersignup_cleanup_controller.go
  controllers/usersignupcleanup/usersignup_cleanup_controller_test.go
Labels: approved

#872 dynamically load targetCluster from Space
  controllers/masteruserrecord/mapper.go
  controllers/masteruserrecord/mapper_test.go
  controllers/masteruserrecord/masteruserrecord_controller.go
  controllers/masteruserrecord/masteruserrecord_controller_test.go
  controllers/masteruserrecord/sync.go
  controllers/masteruserrecord/sync_test.go
  controllers/usersignup/masteruserrecord.go
  controllers/usersignup/masteruserrecord_test.go
  go.mod
  go.sum
  test/spacebinding/spacebinding.go
Labels: approved

#885 Add threshold in codecov settings
  .codecov.yaml
Labels: approved

#868 Set approved to false after user sign up deactivated
  controllers/usersignup/status_updater.go
  controllers/usersignup/usersignup_controller_test.go
Labels: approved, ok-to-test

#888 add CODEOWNERS file
  CODEOWNERS
Labels: approved, lgtm

#884 Add a service for proxy metrics in the registration-service deployment
  controllers/toolchainconfig/toolchainconfig_controller_test.go
  deploy/registration-service/registration-service.yaml
Labels: approved

#886 ASC-402: Modify NSTemplateTierSpec to support SA token copy
  config/crd/bases/toolchain.dev.openshift.com_nstemplatetiers.yaml
Labels: approved, ok-to-test

#878 Adding Pod name for idle email notification
  deploy/templates/notificationtemplates/appstudio/idlertriggered/notification.html
  deploy/templates/notificationtemplates/sandbox/idlertriggered/notification.html
  pkg/templates/notificationtemplates/notification_generator_test.go
Labels: approved, ok-to-test

#890 rename metrics label
  deploy/registration-service/registration-service.yaml
Labels: approved

#889 fix: remove unsupported MUR update from SBR controller
  controllers/spacebindingrequest/spacebindingrequest_controller.go
  controllers/spacebindingrequest/spacebindingrequest_controller_test.go
Labels: approved

#893 fix: replace listpacebindings function with common util
  controllers/space/space_controller.go
  go.mod
  go.sum
Labels: approved

#899 fix: forward context in Space reconciler
  controllers/space/space_controller.go
Labels: approved

#900 update kube-rbac-proxy to v4.13.0
  config/manager/manager.yaml
Labels: approved, lgtm

#895 fix: forward context in SpaceCleanup controller
  controllers/spacecleanup/space_cleanup_controller.go
Labels: approved, lgtm

#894 fix: forward context in SpaceCompletion reconciler
  controllers/spacecompletion/space_completion_controller.go
Labels: approved, lgtm

#896 fix: forward context in SpaceBindingRequest reconciler
  controllers/spacebindingrequest/spacebindingrequest_controller.go
Labels: approved, lgtm

#897 fix: forward context in SpaceBindingCleanup reconciler
  controllers/spacebindingcleanup/spacebinding_cleanup_controller.go
Labels: approved, lgtm

#904 Increase resource quota for appstudilo tier
  deploy/templates/nstemplatetiers/appstudio/cluster.yaml
  deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml
Labels: approved

#887 test.mk get PR branch from CLONEREFS_OPTIONS
  make/test.mk
Labels: approved, ok-to-test

#903 Update CNV network policy
  deploy/templates/nstemplatetiers/base/ns_dev.yaml
  deploy/templates/nstemplatetiers/base/ns_stage.yaml
  deploy/templates/nstemplatetiers/base1ns/ns_dev.yaml
Labels: approved

#907 Align resource quota in base tier with base1ns
  deploy/templates/nstemplatetiers/advanced/based_on_tier.yaml
  deploy/templates/nstemplatetiers/base/cluster.yaml
  deploy/templates/nstemplatetiers/base/ns_dev.yaml
  deploy/templates/nstemplatetiers/base/ns_stage.yaml
  deploy/templates/nstemplatetiers/baselarge/based_on_tier.yaml
Labels: approved
