Repository codeready-toolchain/host-operator, pull requests merged in 2023-09, with the labels that each got.

#857 feat: update SpaceBinding cleanup controller to delete SBR resources
  controllers/spacebindingcleanup/spacebinding_cleanup_controller.go
  controllers/spacebindingcleanup/spacebinding_cleanup_controller_test.go
  controllers/spacebindingrequest/spacebindingrequest_controller.go
  controllers/spacerequest/spacerequest_controller.go
  go.mod
  go.sum
  main.go
  pkg/cluster/cluster.go
Labels: approved

#850 Generated from API
  config/crd/bases/toolchain.dev.openshift.com_masteruserrecords.yaml
  config/crd/bases/toolchain.dev.openshift.com_usersignups.yaml
Labels: approved

#861 Added email to propagated claims
  config/crd/bases/toolchain.dev.openshift.com_masteruserrecords.yaml
Labels: approved

#862 resources: increase the PVC claim limit to 30
  deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml
Labels: approved, ok-to-test

#860 Update notification.html
  deploy/templates/notificationtemplates/appstudio/userprovisioned/notification.html
  pkg/templates/notificationtemplates/notification_generator_test.go
Labels: approved, lgtm, ok-to-test

#863 Propagated identity claims from UserSignup to MasterUserRecord
  controllers/usersignup/masteruserrecord.go
  controllers/usersignup/masteruserrecord_test.go
  go.mod
  go.sum
Labels: approved

#864 Propagate PropagatedClaims from MasterUserRecord to UserAccount
  controllers/masteruserrecord/masteruserrecord_controller.go
  controllers/masteruserrecord/masteruserrecord_controller_test.go
  go.mod
  go.sum
Labels: approved

#865 support email lists for admins
  controllers/toolchainstatus/toolchainstatus_controller.go
  controllers/toolchainstatus/toolchainstatus_controller_test.go
  go.mod
  go.sum
Labels: approved, lgtm

#867 fix: check conflicts with Space name for complaintUsername
  controllers/usersignup/usersignup_controller.go
  controllers/usersignup/usersignup_controller_test.go
Labels: approved
