Repository codeready-toolchain/host-operator, pull requests merged in 2023-03, with the labels that each got.

#756 regenerated from API
  config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml
Labels: approved

#757 refactor logic to check space creation
  controllers/usersignup/usersignup_controller.go
Labels: approved

#758 PLNSRVCE-1164: add new CRD to capture proxy plugin configuration for the registration service
  PROJECT
  config/crd/bases/toolchain.dev.openshift.com_proxyplugins.yaml
  config/manifests/bases/host-operator.clusterserviceversion.yaml
Labels: approved, ok-to-test

#755 refactor: ignore NSTemplateSet creation failure if already exists
  controllers/space/space_controller.go
Labels: approved

#751 feat: create the basic SpaceRequest controller skeleton
  PROJECT
  config/crd/bases/toolchain.dev.openshift.com_spacerequests.yaml
  config/crd/kustomization.yaml
  config/manifests/bases/host-operator.clusterserviceversion.yaml
  controllers/spacerequest/spacerequest_controller.go
  controllers/spacerequest/spacerequest_controller_test.go
  controllers/toolchainconfig/configuration.go
  go.mod
  go.sum
  main.go
  test/spacerequest/spacerequest.go
Labels: approved

#754 enable selection of emails as per environment
  config/crd/bases/toolchain.dev.openshift.com_proxyplugins.yaml
  config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml
  controllers/masteruserrecord/sync.go
  controllers/notification/mailgun_notification_delivery_service.go
  controllers/notification/mailgun_notification_delivery_service_test.go
  controllers/notification/notification_controller.go
  controllers/notification/notification_controller_test.go
  controllers/notification/notification_delivery_service.go
  controllers/notification/notification_delivery_service_test.go
  controllers/toolchainconfig/configuration.go
  controllers/toolchainconfig/configuration_test.go
  controllers/usersignup/usersignup_controller.go
  deploy/resources.go
  deploy/templates/notificationtemplates/appstudio/idlertriggered/notification.html
  deploy/templates/notificationtemplates/appstudio/idlertriggered/subject.txt
  deploy/templates/notificationtemplates/appstudio/userdeactivated/notification.html
  deploy/templates/notificationtemplates/appstudio/userdeactivated/subject.txt
  deploy/templates/notificationtemplates/appstudio/userdeactivating/notification.html
  deploy/templates/notificationtemplates/appstudio/userdeactivating/subject.txt
  deploy/templates/notificationtemplates/appstudio/userprovisioned/notification.html
  deploy/templates/notificationtemplates/appstudio/userprovisioned/subject.txt
  deploy/templates/notificationtemplates/sandbox/idlertriggered/notification.html
  deploy/templates/notificationtemplates/sandbox/idlertriggered/subject.txt
  deploy/templates/notificationtemplates/sandbox/userdeactivated/notification.html
  deploy/templates/notificationtemplates/sandbox/userdeactivated/subject.txt
  deploy/templates/notificationtemplates/sandbox/userdeactivating/notification.html
  deploy/templates/notificationtemplates/sandbox/userdeactivating/subject.txt
  deploy/templates/notificationtemplates/sandbox/userprovisioned/notification.html
  deploy/templates/notificationtemplates/sandbox/userprovisioned/subject.txt
  go.mod
  go.sum
  make/go.mk
  pkg/templates/notificationtemplates/notification_generator.go
  pkg/templates/notificationtemplates/notification_generator_test.go
  pkg/templates/notificationtemplates/testTemplates/fakeNotificationTemplates/appstudio/userprovisioned/test.txt
  pkg/templates/notificationtemplates/testTemplates/fakeNotificationTemplates/sandbox/notification.html
  pkg/templates/notificationtemplates/test_resources.go
Labels: approved

#761 fix: revert removed CRD updates & add ProxyPlugins to the list
  config/crd/bases/toolchain.dev.openshift.com_proxyplugins.yaml
  config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml
  config/crd/kustomization.yaml
Labels: approved, lgtm

#759 fix: preferred cluster disrupts balanced provisioning of users
  pkg/capacity/manager.go
  pkg/capacity/manager_test.go
Labels: approved

#763 PLNSRVCE-1166: add proxyplugins crd to registration-service role
  deploy/registration-service/registration-service.yaml
Labels: approved, lgtm, ok-to-test

#764 feat(HACBS-1969): add read rbac of DT, DTC and DeploymentTargetClass to nstemplatetiers
  deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
Labels: approved, ok-to-test

#766 Allow create access for SelfSubjectAccessReview
  deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
Labels: approved, ok-to-test

#769 Revert PR #766
  deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
Labels: approved, ok-to-test

#768 chore: increase quota for ingresses / routes to 30
  deploy/templates/nstemplatetiers/appstudio/cluster.yaml
  deploy/templates/nstemplatetiers/base/cluster.yaml
  deploy/templates/nstemplatetiers/base1ns/cluster.yaml
  deploy/templates/nstemplatetiers/test/cluster.yaml
Labels: approved

#771 update rbac for DT/DTC/DTCLS
  deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
Labels: approved, ok-to-test

#774 chore: upgrade GolangCI Lint to v1.52.0
  .github/workflows/ci-build.yml
Labels: approved

#779 Add userID and accountID to signup event in segment
  controllers/usersignup/usersignup_controller.go
  pkg/segment/segment.go
  test/segment/assertions.go
Labels: approved

#778 Increase storage limit to 40Gi
  deploy/templates/nstemplatetiers/base/cluster.yaml
  deploy/templates/nstemplatetiers/base1ns/ns_dev.yaml
  deploy/templates/nstemplatetiers/test/ns_dev.yaml
Labels: approved

#780 Rename account_id to groupID for segment
  pkg/segment/segment.go
  test/segment/assertions.go
Labels: approved
