Repository codeready-toolchain/host-operator, pull requests merged in 2024-03, with the labels that each got.

#975 Update User Cleanup controller to be useful
  controllers/usersignupcleanup/usersignup_cleanup_controller.go
  controllers/usersignupcleanup/usersignup_cleanup_controller_test.go
Labels: approved

#979 chore: keeping our GitHub Actions up to date with Dependabot
  .github/dependabot.yml
Labels: approved

#974 Create templates with host ToolchainCluster-related manifests
  deploy/resources.go
  deploy/templates/toolchaincluster/host-sa.yaml
Labels: approved

#985 address linter issues
  .golangci.yml
  controllers/deactivation/deactivation_controller_test.go
  controllers/deactivation/mapper_test.go
  controllers/masteruserrecord/mapper_test.go
  controllers/masteruserrecord/masteruserrecord_controller_test.go
  controllers/masteruserrecord/sync_test.go
  controllers/notification/notification_controller_test.go
  controllers/nstemplatetier/nstemplatetier_controller_test.go
  controllers/socialevent/socialevent_controller_test.go
  controllers/spacebindingcleanup/spacebinding_cleanup_controller_test.go
  controllers/spacerequest/spacerequest_controller_test.go
  controllers/toolchainconfig/sync_test.go
  controllers/toolchainconfig/toolchainconfig_controller_test.go
  controllers/toolchainstatus/toolchainstatus_controller_test.go
  controllers/usersignup/status_updater_test.go
  controllers/usersignup/usersignup_controller_test.go
  controllers/usersignupcleanup/usersignup_cleanup_controller_test.go
  pkg/counter/cache_test.go
  pkg/pending/cache_test.go
  test/metric.go
  test/notification/assertion.go
Labels: approved, lgtm

#978 RHTAPSRE-439: Deploy CA bundle configmap
  deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml
Labels: approved, ok-to-test

#971 KSPACE-20: Drop the distinction between host & member ToolchainClusters
  controllers/masteruserrecord/masteruserrecord_controller_test.go
  controllers/masteruserrecord/sync_test.go
  controllers/space/space_controller_test.go
  controllers/spacebindingcleanup/spacebinding_cleanup_controller_test.go
  controllers/spacebindingrequest/spacebindingrequest_controller_test.go
  controllers/spacerequest/spacerequest_controller_test.go
  controllers/toolchainstatus/toolchainstatus_controller_test.go
  go.mod
  go.sum
  main.go
  test/cluster.go
Labels: approved

#992 Regenerated from API
  config/crd/bases/toolchain.dev.openshift.com_usersignups.yaml
Labels: approved

#993 Increase appstudio pods quota
  deploy/templates/nstemplatetiers/appstudio/cluster.yaml
Labels: approved, ok-to-test

#995 Use `go list` in the go.mod replacements check to improve reliability
  .github/workflows/ci-check-gomod.yml
Labels: approved, lgtm

#996 Increase appstudio tier pvc quota
  deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml
Labels: approved, ok-to-test

#997 cleanup packages being imported more than once
  controllers/masteruserrecord/masteruserrecord_controller_test.go
  controllers/masteruserrecord/sync_test.go
  controllers/notification/notification_controller_test.go
  controllers/spacerequest/space_spacerequest_mapper_test.go
  controllers/spacerequest/spacerequest_controller_test.go
  controllers/toolchainconfig/toolchainconfig_controller_test.go
  pkg/space/space_test.go
  test/counter.go
  test/spacebinding/spacebinding.go
Labels: approved

#991 KSPACE-46: Use SpaceProvisionerConfig for space placement decisions
  config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml
  controllers/deactivation/deactivation_controller_test.go
  controllers/spacecompletion/space_completion_controller_test.go
  controllers/toolchainconfig/configuration.go
  controllers/toolchainconfig/configuration_test.go
  controllers/toolchainconfig/toolchainconfig_controller_test.go
  controllers/usersignup/approval_test.go
  controllers/usersignup/usersignup_controller_test.go
  go.mod
  go.sum
  main.go
  pkg/capacity/manager.go
  pkg/capacity/manager_test.go
  test/spaceprovisionerconfig/util.go
Labels: approved, do-not-merge/hold

#1005 Fix codecov upload error
  .github/workflows/ci-build.yml
Labels: approved
