Repository codeready-toolchain/host-operator, pull requests merged in 2024-05, with the labels that each got.

#1022 KUBESAW-43: Make LastProbeTime optional
  config/crd/bases/toolchain.dev.openshift.com_toolchainclusters.yaml
  config/crd/bases/toolchain.dev.openshift.com_toolchainstatuses.yaml
Labels: approved

#1023 Add network policies for rhoai
  deploy/templates/nstemplatetiers/base/ns_dev.yaml
  deploy/templates/nstemplatetiers/base/ns_stage.yaml
  deploy/templates/nstemplatetiers/base1ns/ns_dev.yaml
Labels: approved, lgtm

#1024 Increase memory quota for rhoai
  deploy/templates/nstemplatetiers/base1ns/ns_dev.yaml
Labels: approved

#1019 Signup controller changes for domain constrained auto-approval
  controllers/toolchainconfig/configuration.go
  controllers/toolchainconfig/configuration_test.go
  controllers/usersignup/approval.go
  controllers/usersignup/approval_test.go
  go.mod
  go.sum
Labels: approved, ok-to-test

#1026 Removing Owners File
  OWNERS
  go.mod
  go.sum
Labels: approved, lgtm

#1025 KUBESAW-43: Introduce LastUpdatedTime as prefered one
  controllers/toolchainstatus/toolchainstatus_controller_test.go
  go.mod
  go.sum
Labels: approved

#1030 KUBESAW-16: Update the go.mod to use toolchaincluster controller from the toolchain-common KUBESAW-16
  go.mod
  go.sum
Labels: approved

#988 Modify DeactivationService to set scheduled deactivation time for active UserSignups
  controllers/deactivation/deactivation_controller.go
  controllers/deactivation/deactivation_controller_test.go
  controllers/deactivation/predicate.go
  controllers/usersignup/status_updater.go
  controllers/usersignup/usersignup_controller.go
  controllers/usersignup/usersignup_controller_test.go
Labels: approved

#1032 Remove michael's name from reviewers
  OWNERS
Labels: approved, lgtm

#1034 Role and RoleBinding for SecretStore and ExternalSecret CRs
  deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
Labels: approved, ok-to-test

#1037 Allow users to manage ImageRepository objects with the same access level as Components
  deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
  deploy/templates/nstemplatetiers/appstudio/spacerole_contributor.yaml
  deploy/templates/nstemplatetiers/appstudio/spacerole_maintainer.yaml
Labels: approved, ok-to-test

#1017 KUBESAW-43: Replace the special ToolchainClusterCondition with the standard toolchain Condition
  config/crd/bases/toolchain.dev.openshift.com_toolchainclusters.yaml
  config/crd/bases/toolchain.dev.openshift.com_toolchainstatuses.yaml
  controllers/toolchainstatus/toolchainstatus_controller_test.go
  go.mod
  go.sum
  test/cluster.go
Labels: approved

#1038 Remove version from apiGroups
  deploy/templates/nstemplatetiers/appstudio/spacerole_admin.yaml
Labels: approved, ok-to-test

#1036 Updatedisablehost
  config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml
Labels: approved, lgtm
