Repository codeready-toolchain/host-operator, pull requests merged in 2025-03, with the labels that each got.

#1151 fix: panic when GH api returns an error
  go.mod
  go.sum
Labels: approved

#1149 feat: manage ready condition in NSTemplatetier
  controllers/nstemplatetier/nstemplatetier_controller.go
  controllers/nstemplatetier/nstemplatetier_controller_test.go
  go.mod
  go.sum
  test/nstemplatetier/assertion.go
Labels: approved

#1152 adjust buckets in provision time histogram
  controllers/usersignup/usersignup_controller_test.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: approved

#1144 SANDBOX-808: update controller-gen.kubebuilder.io/version to v0.15.0
  config/crd/bases/toolchain.dev.openshift.com_bannedusers.yaml
  config/crd/bases/toolchain.dev.openshift.com_masteruserrecords.yaml
  config/crd/bases/toolchain.dev.openshift.com_notifications.yaml
  config/crd/bases/toolchain.dev.openshift.com_nstemplatetiers.yaml
  config/crd/bases/toolchain.dev.openshift.com_proxyplugins.yaml
  config/crd/bases/toolchain.dev.openshift.com_socialevents.yaml
  config/crd/bases/toolchain.dev.openshift.com_spacebindingrequests.yaml
  config/crd/bases/toolchain.dev.openshift.com_spacebindings.yaml
  config/crd/bases/toolchain.dev.openshift.com_spaceprovisionerconfigs.yaml
  config/crd/bases/toolchain.dev.openshift.com_spacerequests.yaml
  config/crd/bases/toolchain.dev.openshift.com_spaces.yaml
  config/crd/bases/toolchain.dev.openshift.com_tiertemplaterevisions.yaml
  config/crd/bases/toolchain.dev.openshift.com_tiertemplates.yaml
  config/crd/bases/toolchain.dev.openshift.com_toolchainclusters.yaml
  config/crd/bases/toolchain.dev.openshift.com_toolchainconfigs.yaml
  config/crd/bases/toolchain.dev.openshift.com_toolchainstatuses.yaml
  config/crd/bases/toolchain.dev.openshift.com_usersignups.yaml
  config/crd/bases/toolchain.dev.openshift.com_usertiers.yaml
Labels: approved

#1146 SANDBOX-808: update kube & openshift dependencies to 4.17
  .github/workflows/govulncheck.yml
  README.adoc
  controllers/masteruserrecord/masteruserrecord_controller.go
  controllers/space/space_controller.go
  controllers/spacebindingrequest/spacebindingrequest_controller.go
  controllers/spaceprovisionerconfig/spaceprovisionerconfig_controller_test.go
  controllers/spacerequest/spacerequest_controller.go
  go.mod
  go.sum
  openshift-ci/Dockerfile.tools
  pkg/counter/cache_test.go
  pkg/templates/usertiers/usertier_generator_whitebox_test.go
  test/spacebinding/spacebinding_assertions.go
Labels: approved

#1156 revert go-version-file usage in govulncheck gh action
  .github/workflows/govulncheck.yml
Labels: approved, lgtm

#1159 chore: Remove kanika from owners
  CODEOWNERS
  OWNERS
Labels: approved, lgtm

#1153 KUBESAW-264: Implement TierTemplateRevision cleanup controller
  controllers/nstemplatetierrevisioncleanup/nstemplatetier_revision_cleanup_controller.go
  controllers/nstemplatetierrevisioncleanup/nstemplatetier_revision_cleanup_controller_test.go
  main.go
Labels: approved

#1160 upgrade operator-sdk and kubebuilder for openshift 4.17
  PROJECT
  cmd/main.go
  make/get-tool.mk
  make/go.mk
Labels: approved

#1158 KUBESAW-201: Replace go-bindata with go:embed
  deploy/resources.go
  deploy/templates/registration-service/registration-service.yaml
  make/go.mk
  pkg/templates/registrationservice/template.go
Labels: approved

#1163 chore(build): migrate to golangci-lint@v2 and golangci-lint-action@v7
  .github/workflows/ci-golang-sbom.yml
  .golangci.yml
  cmd/main.go
  controllers/deactivation/deactivation_controller.go
  controllers/deactivation/deactivation_controller_test.go
  controllers/masteruserrecord/masteruserrecord_controller_test.go
  controllers/masteruserrecord/sync_test.go
  controllers/nstemplatetierrevisioncleanup/nstemplatetier_revision_cleanup_controller_test.go
  controllers/socialevent/socialevent_controller.go
  controllers/socialevent/socialevent_controller_test.go
  controllers/space/space_controller_test.go
  controllers/spacebindingcleanup/spacebinding_cleanup_controller.go
  controllers/spacebindingcleanup/spacebinding_cleanup_controller_test.go
  controllers/spacebindingrequest/spacebindingrequest_controller.go
  controllers/spacebindingrequest/spacebindingrequest_controller_test.go
  controllers/spacerequest/spacerequest_controller.go
  controllers/toolchainstatus/toolchainstatus_controller_test.go
  controllers/usersignup/approval_test.go
  controllers/usersignup/predicate.go
  controllers/usersignup/usersignup_controller_test.go
  controllers/usersignupcleanup/usersignup_cleanup_controller.go
  pkg/capacity/manager_test.go
  pkg/space/space_test.go
  pkg/templates/notificationtemplates/notification_generator.go
  pkg/templates/notificationtemplates/notification_generator_test.go
  pkg/templates/usertiers/usertier_generator.go
  pkg/templates/usertiers/usertier_generator_test.go
  pkg/templates/usertiers/usertier_generator_whitebox_test.go
  test/cluster.go
  test/configmap_assertions.go
Labels: approved

#1164 updates language from provisioning to ready in emails
  deploy/templates/notificationtemplates/sandbox/userprovisioned/notification.html
  deploy/templates/notificationtemplates/sandbox/userprovisioned/subject.txt
  pkg/templates/notificationtemplates/notification_generator_test.go
Labels: approved, lgtm, ok-to-test
